changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
      exclude:
        authors:
          - dependabot
    - title: Fixes
      labels:
        - bug
      exclude:
        authors:
          - dependabot
    - title: Documentation
      labels:
        - documentation
      exclude:
        authors:
          - dependabot
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
      exclude:
        authors:
          - dependabot
