blank_issues_enabled: true
contact_links:
  - name: FAQs
    url: https://github.com/BrendenWalker/TandoorNG/blob/develop/docs/faq.md
    about: Please take a look at the FAQs before creating a bug ticket.
