# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0243_rename_tandoor_theme_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shopping_measure',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient_unit_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='count_per_pack',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='shopping_measure_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='amount_grams',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=32, null=True),
        ),
    ]
