# Generated by Django 5.2.15 on 2026-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0244_food_shopping_measure_shoppinglistentry_amount_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketcategory',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
    ]
