# Generated by Django 5.2.15
"""
Normalize count_per_pack and backfill ShoppingListEntry.amount_grams.

Conversion uses only raw row fields (not cookbook.helper.food_pack) so later
helper changes cannot break this historical migration.
"""

from decimal import Decimal, InvalidOperation

from django.core.validators import MinValueValidator
from django.db import migrations, models
from django_scopes import scopes_disabled

# Snapshot of cookbook.helper.food_pack.COUNT_UNIT_NAMES at the time this
# migration was written. Piece/count words only — not cups, grams, or packs.
COUNT_UNIT_NAMES = {
    'each', 'ea', 'piece', 'pieces', 'pcs', 'pc', 'pce', 'item', 'items',
    'egg', 'eggs',
    'unit', 'units',
    'count', 'whole',
    'stk', 'stück', 'stuck', 'stueck', 'stücke', 'stuecke',
    'stuk', 'stuks',
    'pieza', 'piezas',
    'pezzo', 'pezzi', 'pz',
    'unidade', 'unidades',
    'szt',
    'ks', 'kus',
    'шт', 'штука',
    '个',
}

# Snapshot of UnitConversionHelper weight factors converted to grams
# (amount_g = amount * 1000 / CONVERSION_TABLE['weight'][base_unit]).
WEIGHT_TO_GRAMS = {
    'g': Decimal('1'),
    'kg': Decimal('1000'),
    'ounce': Decimal('1000') / Decimal('35.274'),
    'pound': Decimal('1000') / Decimal('2.20462'),
}

UPDATE_FIELDS = ('amount', 'unit_id', 'amount_grams')
BATCH_SIZE = 500


def _to_decimal(value):
    if value is None or value == '':
        return None
    try:
        d = Decimal(str(value))
    except (InvalidOperation, ValueError, TypeError):
        return None
    if not d.is_finite():
        return None
    return d


def _normalize_unit_name(name):
    return str(name or '').strip().lower().rstrip('.')


def _quantity_to_grams(
    amount,
    unit_id,
    unit_name,
    unit_base,
    ingredient_unit_grams,
    shopping_measure,
    shopping_measure_grams,
):
    """Convert amount+unit to grams using pack fields and weight base units only."""
    amount = _to_decimal(amount)
    if amount is None:
        return None

    if unit_base in WEIGHT_TO_GRAMS:
        return amount * WEIGHT_TO_GRAMS[unit_base]

    iug = _to_decimal(ingredient_unit_grams)
    is_count = unit_id is None or _normalize_unit_name(unit_name) in COUNT_UNIT_NAMES
    if is_count and iug is not None and iug > 0:
        return amount * iug

    smg = _to_decimal(shopping_measure_grams)
    measure = str(shopping_measure or '').strip().lower()
    name = _normalize_unit_name(unit_name)
    if unit_id is not None and measure and name == measure and smg is not None and smg > 0:
        return amount * smg

    return None


def packed_entry_quantities(
    amount,
    unit_id,
    unit_name,
    unit_base,
    ingredient_unit_grams,
    shopping_measure,
    shopping_measure_grams,
):
    """Return (amount, unit_id, amount_grams) from raw shopping-entry / food fields."""
    amount = _to_decimal(amount)
    if amount is None:
        amount = Decimal(0)

    grams = _quantity_to_grams(
        amount,
        unit_id,
        unit_name,
        unit_base,
        ingredient_unit_grams,
        shopping_measure,
        shopping_measure_grams,
    )
    smg = _to_decimal(shopping_measure_grams)
    if grams is not None and smg is not None and smg > 0:
        return grams / smg, None, grams

    return amount, unit_id, grams


def backfill_shopping_amount_grams(apps, schema_editor):
    Food = apps.get_model('cookbook', 'Food')
    ShoppingListEntry = apps.get_model('cookbook', 'ShoppingListEntry')

    with scopes_disabled():
        Food.objects.filter(count_per_pack__lt=1).update(count_per_pack=None)
        entries = (
            ShoppingListEntry.objects
            .filter(amount_grams__isnull=True, food__shopping_measure_grams__isnull=False)
            .exclude(food__shopping_measure_grams__lte=0)
            .values(
                'id',
                'amount',
                'unit_id',
                'unit__name',
                'unit__base_unit',
                'food__ingredient_unit_grams',
                'food__shopping_measure',
                'food__shopping_measure_grams',
            )
        )
        to_update = []
        for row in entries.iterator(chunk_size=BATCH_SIZE):
            amount, unit_id, grams = packed_entry_quantities(
                amount=row['amount'],
                unit_id=row['unit_id'],
                unit_name=row['unit__name'],
                unit_base=row['unit__base_unit'],
                ingredient_unit_grams=row['food__ingredient_unit_grams'],
                shopping_measure=row['food__shopping_measure'],
                shopping_measure_grams=row['food__shopping_measure_grams'],
            )
            if grams is None:
                continue
            to_update.append(ShoppingListEntry(
                pk=row['id'],
                amount=amount,
                unit_id=unit_id,
                amount_grams=grams,
            ))
            if len(to_update) >= BATCH_SIZE:
                ShoppingListEntry.objects.bulk_update(to_update, UPDATE_FIELDS)
                to_update = []
        if to_update:
            ShoppingListEntry.objects.bulk_update(to_update, UPDATE_FIELDS)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0245_supermarketcategory_is_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='count_per_pack',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[MinValueValidator(1)]),
        ),
        migrations.RunPython(backfill_shopping_amount_grams, noop),
    ]
