# Generated by Django 5.2.15
"""
Normalize count_per_pack and backfill ShoppingListEntry.amount_grams.

Conversion logic is frozen in this file (not imported from cookbook.helper.food_pack)
so later helper changes cannot break this historical migration.
"""

from decimal import Decimal, InvalidOperation

from django.core.validators import MinValueValidator
from django.db import migrations, models
from django_scopes import scopes_disabled

# Snapshot of cookbook.helper.food_pack.COUNT_UNIT_NAMES at the time this
# migration was written. Piece/count words only — not cups, grams, or packs.
COUNT_UNIT_NAMES = {
    'each', 'ea', 'piece', 'pieces', 'pcs', 'pc', 'pce', 'item', 'items',
    'egg', 'eggs',
    'unit', 'units',
    'count', 'whole',
    'stk', 'stück', 'stuck', 'stueck', 'stücke', 'stuecke',
    'stuk', 'stuks',
    'pieza', 'piezas',
    'pezzo', 'pezzi', 'pz',
    'unidade', 'unidades',
    'szt',
    'ks', 'kus',
    'шт', 'штука',
    '个',
}

# Snapshot of UnitConversionHelper weight factors converted to grams
# (amount_g = amount * 1000 / CONVERSION_TABLE['weight'][base_unit]).
WEIGHT_TO_GRAMS = {
    'g': Decimal('1'),
    'kg': Decimal('1000'),
    'ounce': Decimal('1000') / Decimal('35.274'),
    'pound': Decimal('1000') / Decimal('2.20462'),
}


def _to_decimal(value):
    if value is None or value == '':
        return None
    try:
        d = Decimal(str(value))
    except (InvalidOperation, ValueError, TypeError):
        return None
    if not d.is_finite():
        return None
    return d


def _unit_name(unit):
    if unit is None:
        return ''
    return str(getattr(unit, 'name', '') or '').strip().lower().rstrip('.')


def _is_count_unit(unit):
    if unit is None:
        return True
    return _unit_name(unit) in COUNT_UNIT_NAMES


def quantity_to_grams(food, amount, unit):
    """Convert amount+unit to grams using pack fields and weight base units only."""
    amount = _to_decimal(amount)
    if amount is None or food is None:
        return None

    base = getattr(unit, 'base_unit', None) if unit is not None else None
    if base in WEIGHT_TO_GRAMS:
        return amount * WEIGHT_TO_GRAMS[base]

    iug = _to_decimal(getattr(food, 'ingredient_unit_grams', None))
    if _is_count_unit(unit) and iug is not None and iug > 0:
        return amount * iug

    smg = _to_decimal(getattr(food, 'shopping_measure_grams', None))
    shopping_measure = str(getattr(food, 'shopping_measure', None) or '').strip().lower()
    if unit is not None and shopping_measure and _unit_name(unit) == shopping_measure and smg is not None and smg > 0:
        return amount * smg

    return None


def shopping_entry_quantities(food, amount, unit):
    """Return (amount, unit, amount_grams) to persist on ShoppingListEntry."""
    amount = _to_decimal(amount)
    if amount is None:
        amount = Decimal(0)

    grams = quantity_to_grams(food, amount, unit)
    smg = _to_decimal(getattr(food, 'shopping_measure_grams', None))
    if grams is not None and smg is not None and smg > 0:
        return grams / smg, None, grams

    return amount, unit, grams


def backfill_shopping_amount_grams(apps, schema_editor):
    Food = apps.get_model('cookbook', 'Food')
    ShoppingListEntry = apps.get_model('cookbook', 'ShoppingListEntry')

    with scopes_disabled():
        Food.objects.filter(count_per_pack__lt=1).update(count_per_pack=None)
        entries = (
            ShoppingListEntry.objects
            .filter(amount_grams__isnull=True, food__shopping_measure_grams__isnull=False)
            .exclude(food__shopping_measure_grams__lte=0)
            .select_related('food', 'unit')
        )
        to_update = []
        for sle in entries.iterator():
            amount, unit, grams = shopping_entry_quantities(sle.food, sle.amount, sle.unit)
            if grams is None:
                continue
            sle.amount = amount
            sle.unit_id = None if unit is None else unit.pk
            sle.amount_grams = grams
            to_update.append(sle)
            if len(to_update) >= 500:
                ShoppingListEntry.objects.bulk_update(to_update, ['amount', 'unit', 'amount_grams'])
                to_update = []
        if to_update:
            ShoppingListEntry.objects.bulk_update(to_update, ['amount', 'unit', 'amount_grams'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0245_supermarketcategory_is_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='count_per_pack',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[MinValueValidator(1)]),
        ),
        migrations.RunPython(backfill_shopping_amount_grams, noop),
    ]
