# Generated by Django 5.2.15

from django.core.validators import MinValueValidator
from django.db import migrations, models
from django_scopes import scopes_disabled


def backfill_shopping_amount_grams(apps, schema_editor):
    Food = apps.get_model('cookbook', 'Food')
    ShoppingListEntry = apps.get_model('cookbook', 'ShoppingListEntry')
    from cookbook.helper.food_pack import shopping_entry_quantities

    with scopes_disabled():
        Food.objects.filter(count_per_pack__lt=1).update(count_per_pack=None)
        entries = (
            ShoppingListEntry.objects
            .filter(amount_grams__isnull=True, food__shopping_measure_grams__isnull=False)
            .exclude(food__shopping_measure_grams__lte=0)
            .select_related('food', 'unit')
        )
        to_update = []
        for sle in entries.iterator():
            amount, unit, grams = shopping_entry_quantities(sle.food, sle.amount, sle.unit)
            if grams is None:
                continue
            sle.amount = amount
            sle.unit = unit
            sle.amount_grams = grams
            to_update.append(sle)
            if len(to_update) >= 500:
                ShoppingListEntry.objects.bulk_update(to_update, ['amount', 'unit', 'amount_grams'])
                to_update = []
        if to_update:
            ShoppingListEntry.objects.bulk_update(to_update, ['amount', 'unit', 'amount_grams'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0245_supermarketcategory_is_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='count_per_pack',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[MinValueValidator(1)]),
        ),
        migrations.RunPython(backfill_shopping_amount_grams, noop),
    ]
