# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0246_food_count_per_pack_min_backfill_amount_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='kcal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='kcal_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=16, null=True),
        ),
    ]
