# Generated by Django 5.2.15
"""
Copy Calories and shopping-measure-grams properties onto Food fields when null.

Does not overwrite existing Food.kcal / kcal_grams / shopping_measure_grams.
Leaves property rows in place.
"""

from decimal import Decimal, InvalidOperation

from django.db import migrations
from django_scopes import scopes_disabled

WEIGHT_TO_GRAMS = {
    'g': Decimal('1'),
    'kg': Decimal('1000'),
    'ounce': Decimal('1000') / Decimal('35.274'),
    'pound': Decimal('1000') / Decimal('2.20462'),
}
GRAM_UNIT_NAMES = {'g', 'gram', 'grams'}
CALORIES_UNITS = {'kcal', 'kcal.'}
SHOPPING_MEASURE_NAME = 'grams in shopping measure'
BATCH_SIZE = 500


def _to_decimal(value):
    if value is None or value == '':
        return None
    try:
        d = Decimal(str(value))
    except (InvalidOperation, ValueError, TypeError):
        return None
    if not d.is_finite():
        return None
    return d


def _normalize(value):
    return str(value or '').strip().lower().rstrip('.')


def is_calories_property_type(property_type):
    if getattr(property_type, 'fdc_id', None) == 1008:
        return True
    if _normalize(getattr(property_type, 'unit', None)) in CALORIES_UNITS:
        return True
    return _normalize(getattr(property_type, 'name', None)) == 'calories'


def is_shopping_measure_grams_property_type(property_type):
    name = _normalize(getattr(property_type, 'name', None))
    unit = _normalize(getattr(property_type, 'unit', None))
    if name == SHOPPING_MEASURE_NAME:
        return True
    if 'shopping measure' in name and unit in GRAM_UNIT_NAMES:
        return True
    return False


def properties_amount_to_grams(amount, unit_name, unit_base):
    amount = _to_decimal(amount)
    if amount is None:
        return None
    base = _normalize(unit_base)
    if base in WEIGHT_TO_GRAMS:
        return amount * WEIGHT_TO_GRAMS[base]
    name = _normalize(unit_name)
    if name in GRAM_UNIT_NAMES:
        return amount
    return None


def calories_property_for_food(food, calories_type_ids):
    for prop in food.properties.all():
        if prop.property_type_id in calories_type_ids and prop.property_amount is not None:
            return prop
    return None


def shopping_grams_property_for_food(food, shopping_type_ids):
    for prop in food.properties.all():
        if prop.property_type_id in shopping_type_ids and prop.property_amount is not None:
            amount = _to_decimal(prop.property_amount)
            if amount is not None and amount > 0:
                return prop
    return None


def backfill_food_kcal_and_shopping_grams(apps, schema_editor):
    Food = apps.get_model('cookbook', 'Food')
    PropertyType = apps.get_model('cookbook', 'PropertyType')
    Unit = apps.get_model('cookbook', 'Unit')

    with scopes_disabled():
        calories_type_ids = [
            pt.id for pt in PropertyType.objects.all() if is_calories_property_type(pt)
        ]
        shopping_type_ids = [
            pt.id for pt in PropertyType.objects.all() if is_shopping_measure_grams_property_type(pt)
        ]

        units = {u.id: u for u in Unit.objects.all()}
        foods = (
            Food.objects.all()
            .prefetch_related('properties', 'properties__property_type')
        )

        to_update = []
        for food in foods:
            changed = False

            if food.kcal is None and food.kcal_grams is None and calories_type_ids:
                calories_prop = calories_property_for_food(food, calories_type_ids)
                if calories_prop is not None:
                    unit = units.get(food.properties_food_unit_id)
                    grams = properties_amount_to_grams(
                        food.properties_food_amount,
                        getattr(unit, 'name', None) if unit else None,
                        getattr(unit, 'base_unit', None) if unit else None,
                    )
                    kcal = _to_decimal(calories_prop.property_amount)
                    if kcal is not None and grams is not None and grams > 0:
                        food.kcal = kcal
                        food.kcal_grams = grams
                        changed = True

            if food.shopping_measure_grams is None and shopping_type_ids:
                shopping_prop = shopping_grams_property_for_food(food, shopping_type_ids)
                if shopping_prop is not None:
                    food.shopping_measure_grams = _to_decimal(shopping_prop.property_amount)
                    changed = True

            if changed:
                to_update.append(food)

            if len(to_update) >= BATCH_SIZE:
                Food.objects.bulk_update(to_update, ['kcal', 'kcal_grams', 'shopping_measure_grams'])
                to_update = []

        if to_update:
            Food.objects.bulk_update(to_update, ['kcal', 'kcal_grams', 'shopping_measure_grams'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0247_food_kcal_kcal_grams'),
    ]

    operations = [
        migrations.RunPython(backfill_food_kcal_and_shopping_grams, noop),
    ]
