# Generated by Django 5.2.15 on 2026-09-08 13:02

import cookbook.models
import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0248_backfill_food_kcal_shopping_measure_grams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=14)),
                ('brand', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='cookbook.food')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            options={
                'ordering': ('upc',),
                'indexes': [models.Index(fields=['upc'], name='cookbook_fo_upc_7dfd68_idx')],
                'constraints': [models.UniqueConstraint(fields=('space', 'upc'), name='food_barcode_unique_upc_per_space')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('food_barcode'), models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
