# Generated by Django 5.2.15 on 2026-09-09

import decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0249_foodbarcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbarcode',
            name='size',
        ),
        migrations.AddField(
            model_name='foodbarcode',
            name='qty',
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0001'))],
            ),
        ),
        migrations.AddField(
            model_name='foodbarcode',
            name='unit',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='cookbook.unit',
            ),
        ),
    ]
