/* tslint:disable */
/* eslint-disable */
/**
 * Stillroom
 * Stillroom API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FoodSimple } from './FoodSimple';
import {
    FoodSimpleFromJSON,
    FoodSimpleFromJSONTyped,
    FoodSimpleToJSON,
    FoodSimpleToJSONTyped,
} from './FoodSimple';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    UnitToJSONTyped,
} from './Unit';

/**
 * Packaged SKU barcode mapped to a generic Food.
 * @export
 * @interface FoodBarcode
 */
export interface FoodBarcode {
    /**
     *
     * @type {number}
     * @memberof FoodBarcode
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof FoodBarcode
     */
    upc: string;
    /**
     *
     * @type {string}
     * @memberof FoodBarcode
     */
    brand?: string | null;
    /**
     *
     * @type {number}
     * @memberof FoodBarcode
     */
    qty?: number;
    /**
     *
     * @type {Unit}
     * @memberof FoodBarcode
     */
    readonly unit?: Unit | null;
    /**
     * Write-only unit primary key.
     * @type {number}
     * @memberof FoodBarcode
     */
    unitId?: number;
    /**
     * Pack size in grams when qty+unit can be converted.
     * @type {number}
     * @memberof FoodBarcode
     */
    readonly grams?: number | null;
    /**
     *
     * @type {FoodSimple}
     * @memberof FoodBarcode
     */
    readonly food: FoodSimple;
    /**
     * Write-only food primary key.
     * @type {number}
     * @memberof FoodBarcode
     */
    foodId?: number;
    /**
     *
     * @type {Date}
     * @memberof FoodBarcode
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the FoodBarcode interface.
 */
export function instanceOfFoodBarcode(value: object): value is FoodBarcode {
    if (!('upc' in value) || value['upc'] === undefined) return false;
    if (!('food' in value) || value['food'] === undefined) return false;
    return true;
}

export function FoodBarcodeFromJSON(json: any): FoodBarcode {
    return FoodBarcodeFromJSONTyped(json, false);
}

export function FoodBarcodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodBarcode {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'upc': json['upc'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'unit': json['unit'] == null ? undefined : UnitFromJSON(json['unit']),
        'unitId': json['unit_id'] == null ? undefined : json['unit_id'],
        'grams': json['grams'] == null ? undefined : json['grams'],
        'food': FoodSimpleFromJSON(json['food']),
        'foodId': json['food_id'] == null ? undefined : json['food_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function FoodBarcodeToJSON(json: any): FoodBarcode {
    return FoodBarcodeToJSONTyped(json, false);
}

export function FoodBarcodeToJSONTyped(value?: Omit<FoodBarcode, 'food'|'unit'|'grams'|'createdAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'upc': value['upc'],
        'brand': value['brand'],
        'qty': value['qty'],
        'unit_id': value['unitId'],
        'food_id': value['foodId'],
    };
}
