/* tslint:disable */
/* eslint-disable */
/**
 * Stillroom
 * Stillroom API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FoodBarcode } from './FoodBarcode';
import {
    FoodBarcodeFromJSON,
    FoodBarcodeFromJSONTyped,
    FoodBarcodeToJSON,
    FoodBarcodeToJSONTyped,
} from './FoodBarcode';

/**
 *
 * @export
 * @interface PaginatedFoodBarcodeList
 */
export interface PaginatedFoodBarcodeList {
    /**
     *
     * @type {number}
     * @memberof PaginatedFoodBarcodeList
     */
    count: number;
    /**
     *
     * @type {string}
     * @memberof PaginatedFoodBarcodeList
     */
    next?: string | null;
    /**
     *
     * @type {string}
     * @memberof PaginatedFoodBarcodeList
     */
    previous?: string | null;
    /**
     *
     * @type {Array<FoodBarcode>}
     * @memberof PaginatedFoodBarcodeList
     */
    results: Array<FoodBarcode>;
    /**
     *
     * @type {Date}
     * @memberof PaginatedFoodBarcodeList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedFoodBarcodeList interface.
 */
export function instanceOfPaginatedFoodBarcodeList(value: object): value is PaginatedFoodBarcodeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedFoodBarcodeListFromJSON(json: any): PaginatedFoodBarcodeList {
    return PaginatedFoodBarcodeListFromJSONTyped(json, false);
}

export function PaginatedFoodBarcodeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFoodBarcodeList {
    if (json == null) {
        return json;
    }
    return {

        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(FoodBarcodeFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedFoodBarcodeListToJSON(json: any): PaginatedFoodBarcodeList {
    return PaginatedFoodBarcodeListToJSONTyped(json, false);
}

export function PaginatedFoodBarcodeListToJSONTyped(value?: PaginatedFoodBarcodeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(FoodBarcodeToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}
