/* tslint:disable */
/* eslint-disable */
/**
 * Stillroom
 * Stillroom API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FoodSimple } from './FoodSimple';
import {
    FoodSimpleFromJSON,
    FoodSimpleFromJSONTyped,
    FoodSimpleToJSON,
    FoodSimpleToJSONTyped,
} from './FoodSimple';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    UnitToJSONTyped,
} from './Unit';

/**
 *
 * @export
 * @interface PatchedFoodBarcode
 */
export interface PatchedFoodBarcode {
    /**
     *
     * @type {number}
     * @memberof PatchedFoodBarcode
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof PatchedFoodBarcode
     */
    upc?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedFoodBarcode
     */
    brand?: string | null;
    /**
     *
     * @type {number}
     * @memberof PatchedFoodBarcode
     */
    qty?: number;
    /**
     *
     * @type {Unit}
     * @memberof PatchedFoodBarcode
     */
    readonly unit?: Unit | null;
    /**
     *
     * @type {number}
     * @memberof PatchedFoodBarcode
     */
    unitId?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedFoodBarcode
     */
    readonly grams?: number | null;
    /**
     *
     * @type {FoodSimple}
     * @memberof PatchedFoodBarcode
     */
    readonly food?: FoodSimple;
    /**
     *
     * @type {number}
     * @memberof PatchedFoodBarcode
     */
    foodId?: number;
    /**
     *
     * @type {Date}
     * @memberof PatchedFoodBarcode
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedFoodBarcode interface.
 */
export function instanceOfPatchedFoodBarcode(value: object): value is PatchedFoodBarcode {
    return true;
}

export function PatchedFoodBarcodeFromJSON(json: any): PatchedFoodBarcode {
    return PatchedFoodBarcodeFromJSONTyped(json, false);
}

export function PatchedFoodBarcodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFoodBarcode {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'upc': json['upc'] == null ? undefined : json['upc'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'unit': json['unit'] == null ? undefined : UnitFromJSON(json['unit']),
        'unitId': json['unit_id'] == null ? undefined : json['unit_id'],
        'grams': json['grams'] == null ? undefined : json['grams'],
        'food': json['food'] == null ? undefined : FoodSimpleFromJSON(json['food']),
        'foodId': json['food_id'] == null ? undefined : json['food_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedFoodBarcodeToJSON(json: any): PatchedFoodBarcode {
    return PatchedFoodBarcodeToJSONTyped(json, false);
}

export function PatchedFoodBarcodeToJSONTyped(value?: Omit<PatchedFoodBarcode, 'food'|'unit'|'grams'|'createdAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'upc': value['upc'],
        'brand': value['brand'],
        'qty': value['qty'],
        'unit_id': value['unitId'],
        'food_id': value['foodId'],
    };
}
