/* tslint:disable */
/* eslint-disable */
/**
 * Stillroom
 * Stillroom API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `BLANK` - -------
 * * `STILLROOM` - Stillroom
 * * `BOOTSTRAP` - Bootstrap
 * * `DARKLY` - Darkly
 * * `FLATLY` - Flatly
 * * `SUPERHERO` - Superhero
 * * `STILLROOM_DARK` - Stillroom Dark (INCOMPLETE)
 * @export
 */
export const SpaceThemeEnum = {
    Blank: 'BLANK',
    Stillroom: 'STILLROOM',
    Bootstrap: 'BOOTSTRAP',
    Darkly: 'DARKLY',
    Flatly: 'FLATLY',
    Superhero: 'SUPERHERO',
    StillroomDark: 'STILLROOM_DARK'
} as const;
export type SpaceThemeEnum = typeof SpaceThemeEnum[keyof typeof SpaceThemeEnum];


export function instanceOfSpaceThemeEnum(value: any): boolean {
    for (const key in SpaceThemeEnum) {
        if (Object.prototype.hasOwnProperty.call(SpaceThemeEnum, key)) {
            if (SpaceThemeEnum[key as keyof typeof SpaceThemeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SpaceThemeEnumFromJSON(json: any): SpaceThemeEnum {
    return SpaceThemeEnumFromJSONTyped(json, false);
}

export function SpaceThemeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceThemeEnum {
    return json as SpaceThemeEnum;
}

export function SpaceThemeEnumToJSON(value?: SpaceThemeEnum | null): any {
    return value as any;
}

export function SpaceThemeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SpaceThemeEnum {
    return value as SpaceThemeEnum;
}

