name: Make Docs
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy:
    if: github.repository_owner == 'BrendenWalker' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-include-markdown-plugin
      - run: mkdocs gh-deploy --force
